language: node_js
node_js:
- 4.1
- 4.0
sudo: false
addons:
  code_climate:
    repo_token:
      secure: jNaDgvGwzVYZAHBdLNOKqHIDUMMrrbURu6pTsKTGl5gAhFdeN2u0Q1vfr9iUdtk3xOfA+IRWRiT1n7dKaAxPBHiHtj0btjYAVhc8DqmmavFOdh82gPc0WCSJ3L3zIhOFbStUDujXJ5xjiQkqREZsUIZmS3z4uAFUB+zILdCtNbT8z6mplPzN5Ljnu28LG7Dz+d/YsY1lbRThQTRTdv1ppQr1w8VTG+Te/3d+0iRXxdvGjggXzDy4bIk9NucMiHxIbs/9z6FhmRFqocWqeEEGZsfuS89B6MGwVSvI7T8pm9TFD/Zx6m3WfLceVOJvgxdexxrhKVtcBqiZTtfC/gRTU10Un+j/wrgSe5CP2pUij/p0h+oLP+jpBe1mteejxScrRPZZVaxYw4CCZIlMJtvzM1sRKXreTIZCrP7vixryYNPuG4i07gPcI0dRI3+LtcsGRElaYA1cK2FvJHkVJH46jEEIahLqLneCz0vlPOkvDth/4feHqUZP9+ihTVvjJLkcCx+aEkkzZjaHC5kDLEIzk5kZR/8ihK3vcSmQ7cMfHSMV3QwA3+h58rHU+V60W3NVVWVr2iX/t5ZtuZIZqeKWcGPnxVHabbGDmd0laZxYpiklx37WEALYgbwMnomM4XflYqSQadXjy9RvFV7itd1gyOUArpU8aMU5fwD6nlkaU1Y=
after_script:
- cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter
- cat coverage/lcov.info | node_modules/.bin/codacy-coverage
env:
  global:
    secure: pRDovxsi6D50QYOSpub9Kq88UGeMfMck5HTrApGbtozQ4u6uUkFO83CoJpW4c5t/G9mCRDK0mFLIF9HyiYgJ8yfh5Wwe1AA7I2dm+OlWjpOyo4ICKY03zYKjNqqP/X4dRNSNV0ZekGQ+iOnA0pMAUc67eaqxgOFEjUWOowyhgyUfIFE2D0zJ8Wmnm7cjfAY60myfvRWiNQ5lXhAalfvON2so0lmIN80nYgrc8Y3TE7jedhMHmEvI9PMRaVg8/rdITW1fhYtbc8pfsSCd57j3OtFw3rO0mXXkmipzOIT+EjoEHTzn2+WdKCwNAMhYBBqXA64SrvJ1GmPRInAGn1vAFnpQh424rEPRLz7kQO7fgM0yl0Zt2DrIMjWYU/BWWiEzrYbwHNP114AZG2f+D+c2IaNfXnoc6OYyO1+pV9+iL50xxo15p8gCgdpGwZqfYjlgsVcTlii5XM4qAcglEo3POcmN/Pb9gkCVV9MwbvyoFBN7emnMPVlah+pOV51FBE182u+mKBqOwlG+UhPILG3WhznHN7maduF6OeOHrPu71WfVoxieywc5DMcVU3AF7W+obnFa8Hd4huqnNV2D0+Otuy3ojc7t59s3WSpEGmO7d92/K48+gWSzc0Lzxt233pb2fFLEgErca9M6r7xbefv8c0JiUXPZdnTSsxEBxCgjj8A=
