language: node_js
node_js:
  - iojs
sudo: false
addons:
  code_climate:
    repo_token:
      secure: "jNaDgvGwzVYZAHBdLNOKqHIDUMMrrbURu6pTsKTGl5gAhFdeN2u0Q1vfr9iUdtk3xOfA+IRWRiT1n7dKaAxPBHiHtj0btjYAVhc8DqmmavFOdh82gPc0WCSJ3L3zIhOFbStUDujXJ5xjiQkqREZsUIZmS3z4uAFUB+zILdCtNbT8z6mplPzN5Ljnu28LG7Dz+d/YsY1lbRThQTRTdv1ppQr1w8VTG+Te/3d+0iRXxdvGjggXzDy4bIk9NucMiHxIbs/9z6FhmRFqocWqeEEGZsfuS89B6MGwVSvI7T8pm9TFD/Zx6m3WfLceVOJvgxdexxrhKVtcBqiZTtfC/gRTU10Un+j/wrgSe5CP2pUij/p0h+oLP+jpBe1mteejxScrRPZZVaxYw4CCZIlMJtvzM1sRKXreTIZCrP7vixryYNPuG4i07gPcI0dRI3+LtcsGRElaYA1cK2FvJHkVJH46jEEIahLqLneCz0vlPOkvDth/4feHqUZP9+ihTVvjJLkcCx+aEkkzZjaHC5kDLEIzk5kZR/8ihK3vcSmQ7cMfHSMV3QwA3+h58rHU+V60W3NVVWVr2iX/t5ZtuZIZqeKWcGPnxVHabbGDmd0laZxYpiklx37WEALYgbwMnomM4XflYqSQadXjy9RvFV7itd1gyOUArpU8aMU5fwD6nlkaU1Y="
after_script:
  - npm install -g codeclimate-test-reporter
  - cat coverage/lcov.info | codeclimate
